// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Chronos/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CancelNotification mocks base method.
func (m *MockService) CancelNotification(ctx context.Context, notificationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelNotification", ctx, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelNotification indicates an expected call of CancelNotification.
func (mr *MockServiceMockRecorder) CancelNotification(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelNotification", reflect.TypeOf((*MockService)(nil).CancelNotification), ctx, notificationID)
}

// CreateNotification mocks base method.
func (m *MockService) CreateNotification(ctx context.Context, notification models.Notification) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, notification)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockServiceMockRecorder) CreateNotification(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockService)(nil).CreateNotification), ctx, notification)
}

// GetAllStatuses mocks base method.
func (m *MockService) GetAllStatuses(ctx context.Context) []models.Notification {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStatuses", ctx)
	ret0, _ := ret[0].([]models.Notification)
	return ret0
}

// GetAllStatuses indicates an expected call of GetAllStatuses.
func (mr *MockServiceMockRecorder) GetAllStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStatuses", reflect.TypeOf((*MockService)(nil).GetAllStatuses), ctx)
}

// GetStatus mocks base method.
func (m *MockService) GetStatus(ctx context.Context, notificationID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, notificationID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockServiceMockRecorder) GetStatus(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockService)(nil).GetStatus), ctx, notificationID)
}
